Import các thư viện cần thiết

In [5]:
import pandas as pd
import numpy as np

# Chuẩn bị dữ liệu
Cho file `temperatures.csv` chứa một vài dữ liệu độ F - độ C.\
Hãy đọc dữ liệu vào DataFrame `df` và quan sát 5 dòng đầu của dữ liệu.

**KẾT QUẢ MONG ĐỢI:**
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Farenheit</th>
      <th>Celcius</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-58.0</td>
      <td>-58</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-40.0</td>
      <td>-40</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-22.0</td>
      <td>-30</td>
    </tr>
    <tr>
      <th>3</th>
      <td>-4.0</td>
      <td>-20</td>
    </tr>
    <tr>
      <th>4</th>
      <td>14.0</td>
      <td>-10</td>
    </tr>
  </tbody>
</table>
</div>

In [6]:
### YOUR CODE HERE
with open("temperatures.csv", "r") as f:
    df = pd.read_csv(f)

df.head()

   Farenheit  Celcius
0      -58.0      -50
1      -40.0      -40
2      -22.0      -30
3       -4.0      -20
4       14.0      -10

Nên chuyển đổi dữ liệu input và output thành dạng `numpy.ndarray` để phù hợp với yêu cầu đầu vào của mạng Neuron.

In [7]:
f_input = df["Farenheit"].to_numpy()
c_output = df["Celcius"].to_numpy()
type(f_input), type(c_output)

(numpy.ndarray, numpy.ndarray)

# Xây dựng - Huấn luyện mô hình

In [8]:
from tensorflow import keras

Mô hình tuần tự `Sequential` cần xây dựng gồm 2 layer `Dense`.\
Layer `Dense` là layer kết nối tất cả các node ở layer trước đến layer sau nó, nhận vào các tham số:
* `units`: số node trong layer Dense (tuỳ chọn)
* `input_shape`: đầu ra của layer Dense (phụ thuộc vào dữ liệu)

Mô hình sẽ được huấn luyện với tham số `loss='mean_squared_error'` và `optimizer='adam'`

**KẾT QUẢ MONG ĐỢI:**
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-weight: bold">Model: "sequential"</span>
</pre>
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace">┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃<span style="font-weight: bold"> Layer (type)                    </span>┃<span style="font-weight: bold"> Output Shape           </span>┃<span style="font-weight: bold">       Param # </span>┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (<span style="color: #0087ff; text-decoration-color: #0087ff">Dense</span>)                │ (<span style="color: #00d7ff; text-decoration-color: #00d7ff">None</span>, <span style="color: #00af00; text-decoration-color: #00af00">10</span>)             │            <span style="color: #00af00; text-decoration-color: #00af00">20</span> │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (<span style="color: #0087ff; text-decoration-color: #0087ff">Dense</span>)                │ (<span style="color: #00d7ff; text-decoration-color: #00d7ff">None</span>, <span style="color: #00af00; text-decoration-color: #00af00">1</span>)              │            <span style="color: #00af00; text-decoration-color: #00af00">11</span> │
└─────────────────────────────────┴────────────────────────┴───────────────┘
</pre>
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-weight: bold"> Total params: </span><span style="color: #00af00; text-decoration-color: #00af00">31</span> (124.00 B)
</pre>
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-weight: bold"> Trainable params: </span><span style="color: #00af00; text-decoration-color: #00af00">31</span> (124.00 B)
</pre>
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-weight: bold"> Non-trainable params: </span><span style="color: #00af00; text-decoration-color: #00af00">0</span> (0.00 B)
</pre>

In [9]:
model = keras.Sequential([                               
    keras.layers.Dense(units=10, input_shape=[1]),
    keras.layers.Dense(units=1)
    ])

model.compile(loss='mean_squared_error',
              optimizer='adam')
model.summary()

/Users/hieu1966hn/Documents/MindX_Teaching/NPS/NPS-CSI16-HB/.venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 10)             │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

Huấn luyện mô hình bằng phương thức `fit` nhận vào các tham số:
* Dữ liệu input (tham số #1)
* Dữ liệu output (tham số #2)
* `epochs`: số lần huấn luyện trên dữ liệu

Trong bài tập này, ta set `epochs=100`.

In [14]:
model.fit(f_input, c_output, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 291.5475
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 288.2065
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 284.9824
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 281.8719
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 278.8717
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 275.9787
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 273.1895
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 270.5009
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 267.9101
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 265.4140
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 263.0095
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 260.6937
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 258.4640
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 256.3174
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 254.2512
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 252.2628
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 250.3496
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 248.5090
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 246.7386
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 245.0358
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 243.3984
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 241.8240
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 240.3104
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 238.8554
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 237.4568
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 236.1124
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 234.8205
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 233.5789
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 232.3857
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 231.2391
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 230.1373
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 229.0784
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 228.0608
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 227.0829
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 226.1430
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 225.2396
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 224.3712
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 223.5363
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 222.7336
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 221.9616
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 221.2190
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 220.5047
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 219.8173
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 219.1556
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 218.5186
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 217.9052
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 217.3142
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 216.7447
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 216.1957
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 215.6662
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 215.1554
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 214.6624
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 214.1862
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 213.7262
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 213.2816
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 212.8516
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 212.4355
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 212.0327
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 211.6424
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 211.2641
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 210.8972
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 210.5411
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 210.1953
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 209.8592
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 209.5324
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 209.2144
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 208.9047
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 208.6029
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 208.3086
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 208.0215
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 207.7410
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 207.4670
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 207.1990
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 206.9368
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 206.6800
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 206.4284
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 206.1816
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 205.9395
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 205.7017
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 205.4681
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 205.2383
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 205.0123
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 204.7899
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 204.5708
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 204.3548
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 204.1418
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 203.9316
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 203.7241
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 203.5191
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 203.3166
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 203.1164
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 202.9183
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 202.7223
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 202.5282
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 202.3359
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 202.1454
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 201.9566
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 201.7694
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 201.5837
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 201.3994

# Dự đoán
Cho độ F cần chuyển đổi là 90.\
Hãy sử dụng phương thức `predict()` của mô hình để dự đoán độ C tương ứng.

In [15]:
input = np.array([90])
prediction = model.predict(input)
print(input, "Degree Farenheit is predicted as", prediction[0], "Degree Celcius")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[90] Degree Farenheit is predicted as [32.5285] Degree Celcius

Hãy sử dụng công thức chuyển đổi truyền thống để tính kết quả độ C chính xác.\
So sánh với kết quả dự đoán của mô hình.

In [12]:
print("Expected value is", (90 - 32)/(1.8), "Degree Celcius")

Expected value is 32.22222222222222 Degree Celcius